### ISSUE TITLE
assignment 4

### ISSUE THREAD

**Issue by xiangbin96** [benjamingarrisonxiangbin/etc3250#4]

**Comment by benjamingarrisonxiangbin** [comment]
![Q1(a)](https://user-images.githubusercontent.com/62995940/82083436-4e7e4d00-971c-11ea-922e-bab7b95c600e.PNG)
![Q1(b)](https://user-images.githubusercontent.com/62995940/82083442-4faf7a00-971c-11ea-8fee-a02947009110.PNG)
![Q1(d)](https://user-images.githubusercontent.com/62995940/82083444-50e0a700-971c-11ea-9110-c3f5fa7b611f.PNG)
![Q1(e)](https://user-images.githubusercontent.com/62995940/82083449-51793d80-971c-11ea-9f43-3f51620cc11c.PNG)
![Q1(g)](https://user-images.githubusercontent.com/62995940/82083451-5211d400-971c-11ea-9d92-d842054cf7e8.PNG)

**Comment by benjamingarrisonxiangbin** [comment]
![Q1(a)](https://user-images.githubusercontent.com/62995940/82085900-445e4d80-9720-11ea-880e-ecad0e86c493.PNG)
![Q1(b)](https://user-images.githubusercontent.com/62995940/82085902-458f7a80-9720-11ea-9bf6-8c37cb67d891.PNG)
![Q1(d)](https://user-images.githubusercontent.com/62995940/82085904-46c0a780-9720-11ea-802a-bd0d7e897a89.PNG)
![Q1(e)](https://user-images.githubusercontent.com/62995940/82085907-46c0a780-9720-11ea-9ace-c16f03fea3f6.PNG)
![Q1(f)](https://user-images.githubusercontent.com/62995940/82085909-47f1d480-9720-11ea-88a0-8e6b4a89755f.PNG)
![Q1(g)](https://user-images.githubusercontent.com/62995940/82085911-47f1d480-9720-11ea-9744-d94a95877b68.PNG)

**Comment by xiangbin96** [comment]
![Q1(b)](https://user-images.githubusercontent.com/62995940/82086447-1cbbb500-9721-11ea-8991-26ee13f65f38.PNG)
![Q1(d)](https://user-images.githubusercontent.com/62995940/82086451-1d544b80-9721-11ea-9bd6-49d503906527.PNG)
![Q1(e)](https://user-images.githubusercontent.com/62995940/82086455-1e857880-9721-11ea-976d-3b4927830f4c.PNG)
![Q1(f)](https://user-images.githubusercontent.com/62995940/82086459-1f1e0f00-9721-11ea-8e29-99b0d41ec205.PNG)
![Q1(g)](https://user-images.githubusercontent.com/62995940/82086462-1fb6a580-9721-11ea-91f2-37f78ab45199.PNG)
![Q1(a)](https://user-images.githubusercontent.com/62995940/82086464-1fb6a580-9721-11ea-85d8-e1f49819f22b.PNG)
